version: "3"

services:
  api01:
    container_name: api01
    build: ./api
    environment:
      - MESSAGE=${MESSAGE}
    ports:
      - 3000:3000

  api02:
    container_name: api02
    build: ./api
    environment:
      - MESSAGE=${MESSAGE}
    ports:
      - 3001:3000

  api03:
    container_name: api03
    build: ./api
    environment:
      - MESSAGE=${MESSAGE}
    ports:
      - 3002:3000

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: